name: pygeoutils-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  # pygeoogc deps
  - cytoolz
  - defusedxml
  - owslib
  - pyproj
  - requests
  - requests-cache
  - setuptools
  - shapely
  - simplejson

  # pygeoutils deps
  - affine
  - geopandas
  - netcdf4
  - rasterio
  - xarray

  # deps to speed up xarray and geopandas
  - pygeos
  - bottleneck

  # test deps
  - pytest
  - pytest-cov
  - pytest-xdist
  - flaky

  - pip
  - pip:
    - git+https://github.com/cheginit/pygeoogc.git
