name: pygeoutils-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  - pip
  - setuptools
  - owslib
  - pyproj
  - shapely
  - orjson
  - simplejson
  - defusedxml
  - requests
  - aiohttp
  - chardet
  - aiodns
  - brotlipy
  - nest-asyncio
  - xarray
  - netCDF4
  - geopandas
  - rasterio
  - pip:
    - git+https://github.com/cheginit/pygeoogc.git
