name: pygeoutils-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  # pygeoogc deps
  - aiodns
  - aiohttp
  - brotlipy
  - chardet
  - cytoolz
  - defusedxml
  - nest-asyncio
  - orjson
  - owslib
  - pyproj
  - requests
  - setuptools
  - shapely
  - simplejson

  # pygeoutils deps
  # - orjson
  - geopandas
  - netCDF4
  - rasterio
  - xarray

  # deps to speed up xarray and geopandas
  - pygeos
  - bottleneck

  # test deps
  - pytest
  - pytest-cov
  - pytest-xdist
  - flaky

  - pip
  - pip:
    - git+https://github.com/cheginit/pygeoogc.git
